"use strict";
function menu_mygtukai_kontaktai() {
    sort.classList.remove("sort_active");
    sort.classList.add("sort_hidden"); 
    hero.classList.add("hero_hidden");
    hero.classList.remove("hero_active");
    hero_mygtukas.classList.remove("hero_mygtukas_active");
    hero_mygtukas.classList.add("hero_mygtukas_hidden");
    content.classList.add("content_large");
    content.classList.remove("content_mid");
    sort_container.classList.remove("sort_container_active");
    sort_container.classList.add("sort_container_hidden");
    naujienos.classList.add("naujienos_hidden");
    card.classList.add("card_hidden");
    apie_mus.classList.add("apie_mus_hidden");
    kontaktai.classList.remove("kontaktai_hidden");
}
function menu_mygtukai_apie_mus() {
    sort.classList.remove("sort_active");
    sort.classList.add("sort_hidden");  
    hero.classList.add("hero_hidden");
    hero.classList.remove("hero_active"); 
    hero_mygtukas.classList.remove("hero_mygtukas_active");
    hero_mygtukas.classList.add("hero_mygtukas_hidden");
    content.classList.remove("content_mid");
    content.classList.add("content_large");
    sort_container.classList.remove("sort_container_active");
    sort_container.classList.add("sort_container_hidden");
    naujienos.classList.add("naujienos_hidden");
    card.classList.add("card_hidden");
    apie_mus.classList.remove("apie_mus_hidden");
    kontaktai.classList.add("kontaktai_hidden");
}
function menu_mygtukai_naujienos() {
    sort.classList.remove("sort_active");
    sort.classList.add("sort_hidden"); 
    hero.classList.add("hero_hidden");
    hero.classList.remove("hero_active");
    hero_mygtukas.classList.remove("hero_mygtukas_active");
    hero_mygtukas.classList.add("hero_mygtukas_hidden");
    content.classList.remove("content_mid");
    content.classList.add("content_large");
    sort_container.classList.remove("sort_container_active");
    sort_container.classList.add("sort_container_hidden");
    naujienos.classList.remove("naujienos_hidden");
    card.classList.add("card_hidden");
    apie_mus.classList.add("apie_mus_hidden");
    kontaktai.classList.add("kontaktai_hidden");
}
function sort_active() {
   console.log("hi");
   
    sort.classList.add("sort_active");
    sort.classList.remove("sort_hidden");
    hero.classList.remove("hero_active");
    hero.classList.add("hero_hidden");
    hero_mygtukas.classList.remove("hero_mygtukas_active");
    hero_mygtukas.classList.add("hero_mygtukas_hidden");
    content.classList.add("content_mid");
    content.classList.remove("content_large");
    sort_container.classList.add("sort_container_active");
    sort_container.classList.remove("sort_container_hidden"); 
    naujienos.classList.add("naujienos_hidden");
    card.classList.remove("card_hidden");
    apie_mus.classList.add("apie_mus_hidden");
    kontaktai.classList.add("kontaktai_hidden");
}
function homepage() {
    sort.classList.remove("sort_active");
    sort.classList.add("sort_hidden"); 
    hero.classList.remove("hero_hidden");
    hero.classList.add("hero_active");
    hero_mygtukas.classList.add("hero_mygtukas_active")
    hero_mygtukas.classList.remove("hero_mygtukas_hidden");
    content.classList.remove("content_mid");
    content.classList.add("content_large");
    sort_container.classList.remove("sort_container_active");
    sort_container.classList.add("sort_container_hidden");
    naujienos.classList.remove("naujienos_hidden");
    card.classList.add("card_hidden");
    apie_mus.classList.add("apie_mus_hidden");
    kontaktai.classList.add("kontaktai_hidden");
}